spring:
  profiles.active: local


---


spring:
  profiles: local

  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: always
  resources:
    add-mappings: false
  rabbitmq:
    host: 172.16.0.29
    port: 5672
    username: guest
    password: guest


elasticsearch:
  clusterName: order-cluster
  host: localhost
  port: 9300

brave:
  kafkaURI: 172.16.1.159:9092

rabbitmq:
    orderQueryDataExchangeName: mu_hll:service:order:querydata:db:exchange
    orderESDataQueueName: mu_hll:service:order:es:db:queue



